service: programs-api

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  environment:
    DB: ${env:DB_CONNECTION_STRING}

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

functions:
# CREATE
  createEndpoint:
    handler: api/create.newEndpoint
    events:
      - http:
          path: api/programs/endpoint
          method: post
          cors: true
# READ
  getAllEndpoints:
    handler: api/read.getAllEndpoints
    events:
      - http:
          path: api/program/all
          method: get
          cors: true
  getOneProgram:
    handler: api/read.getOneProgram
    events:
      - http:
          path: api/program/{dm}/{mt}/{vt}/{lt}/{dt}/{da}/{co}/{do}/{eo}
          method: get
          cors: true
# DELETE
  deleteProgram:
    handler: api/delete.removeProgram
    events:
      - http:
          path: api/program/remove/{dm}/{mt}/{vt}/{lt}/{dt}/{da}/{co}/{do}/{eo}
          method: delete
          cors: true