service: programs-api

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  environment:
    DB: ${env:DB_CONNECTION_STRING}

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

functions:
# CREATE
  createProgram:
    handler: api/create.newProgram
    events:
      - http:
          path: api/program/add
          method: post
          cors: true
# READ
  getAllPrograms:
    handler: api/read.getAllPrograms
    events:
      - http:
          path: api/program/all
          method: get
          cors: true
  getOneProgram:
    handler: api/read.getOneProgram
    events:
      - http:
          path: api/program/endpoints
          method: any
          cors: true
# DELETE
  deleteProgram:
    handler: api/delete.removeProgram
    events:
      - http:
          path: api/program/remove
          method: delete
          cors: true